In [2]:
# use python to solve all the questions
import numpy as np

### Q1. Given the vectors A = [1, 2, 3] and B = [4, 5, 6], calculate the element-wise product of the two vectors.

### Q2. Find the magnitude of the vector C = [2, -3, 1].


### Q3. Given the vectors D = [1, 2, 3] and E = [4, 5, 6], calculate the cosine of the angle between them.

### Q4. Given the vectors F = [1, 2, 3] and G = [4, 5, 6], calculate the cross product of the two vectors.

### Q5. Given the vector H = [2, 4, 6], shift the vector +1 unit in each dimension

### Q6. Given the vectors I = [1, 2, 3] and J = [4, 5, 6], calculate the projection of vector I onto vector J.

### Q7. Consider the 2D - position vector a = (1, 3). If b is the point (5, 4), find the vector `ab` and the vector sum `a + ab`. Provide a sketch plot.

Note: Search for quiver, to plot an arrow.

### Q8. Given two 2D vectors `u` and `v` where `u = [-1, 4]` and `v = [3, -2]`, find the dot product `u . v`, the angle between `u` and `v`, and the projection of `u` onto `v`.


### Q9. Given a hyperplane defined by the equation 3x - 2y + z = 1, find two different points that lie on this hyperplane.

### Q10. Find a nearest point from a given array of points to a point P1.
P1 - (3,9,3)

Array of points :
```
[[1, 8, 5],
[8, 8, 2],
[7, 9, 1],
[5, 6, 3],
[9, 1, 2],
[6, 5, 9],
[5, 8, 6],
[3, 4, 8],
[6, 8, 4],
[7, 2, 7]]
```

Q3. Given the vectors D = [1, 2, 3] and E = [4, 5, 6], calculate the cosine of the angle between them.

In [3]:
D = [1, 2, 3]
E = [4, 5,6]
(np.dot(D,E) /( np.linalg.norm(D) * np.linalg.norm(E)) )

np.float64(0.9746318461970762)

Q4. Given the vectors F = [1, 2, 3] and G = [4, 5, 6], calculate the cross product of the two vectors.

In [4]:
F = [1, 2, 3]
G = [4, 5, 6]
np.cross(F,G)

array([-3,  6, -3])

Q5. Given the vector H = [2, 4, 6], shift the vector +1 unit in each dimension

In [5]:
H = [2, 4, 6]
np.add(H,1)

array([3, 5, 7])

Q6. Given the vectors I = [1, 2, 3] and J = [4, 5, 6], calculate the projection of vector I onto vector J.

In [6]:
I = np.array([1, 2, 3])
J = np.array([4, 5, 6])
(np.dot(I,J)/(np.linalg.norm(J)**2)) * J

array([1.66233766, 2.07792208, 2.49350649])

Q7. Consider the 2D - position vector a = (1, 3). If b is the point (5, 4), find the vector ab and the vector sum a + ab. Provide a sketch plot.

In [7]:
a = np.array([1,3])
b = np.array([5,4])
ab  = b-a
ans = ab + a



In [16]:
ab

array([4, 1])

In [15]:
ans

array([5, 4])

Q8. Given two 2D vectors u and v where u = [-1, 4] and v = [3, -2], find the dot product u . v, the angle between u and v, and the projection of u onto v.

In [8]:
u = np.array([-1, 4])
v = np.array([3, -2])
print(np.dot(u,v))
print(np.dot(u,v) / (np.linalg.norm(u) * np.linalg.norm(v) ))
print((np.dot(u,v)/(np.linalg.norm(v)**2) )* v)

-11
-0.7399400733959438
[-2.53846154  1.69230769]


Q9. Given a hyperplane defined by the equation 3x - 2y + z = 1, find two different points that lie on this hyperplane.

In [9]:
# 1 , 1    -2 , 1

Q10. Find a nearest point from a given array of points to a point P1.
P1 - (3,9,3)

Array of points :

[[1, 8, 5],
[8, 8, 2],
[7, 9, 1],
[5, 6, 3],
[9, 1, 2],
[6, 5, 9],
[5, 8, 6],
[3, 4, 8],
[6, 8, 4],
[7, 2, 7]]

In [10]:
P1 = np.array([3,9,3])

In [11]:
P1

array([3, 9, 3])

In [12]:
check = [[1, 8, 5], [8, 8, 2], [7, 9, 1], [5, 6, 3], [9, 1, 2], [6, 5, 9], [5, 8, 6], [3, 4, 8], [6, 8, 4], [7, 2, 7]]

In [13]:
mini = []
for i in check:
  print(np.linalg.norm(P1-i))
  mini.append(np.linalg.norm(P1-i))

3.0
5.196152422706632
4.47213595499958
3.605551275463989
10.04987562112089
7.810249675906654
3.7416573867739413
7.0710678118654755
3.3166247903554
9.0


In [14]:
print(min(mini))

3.0
