In [56]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [57]:
df = pd.read_csv('/content/pca_dataset.csv')

In [58]:
df.head()

Feature1  Feature2  Feature3  Target
0  0.496714  1.648168 -0.495534       1
1 -0.138264  0.229835 -1.667353       0
2  0.647689 -0.353844 -2.280808       0
3  1.523030  2.223353 -0.974309       1
4 -0.234153  3.061999  2.657458       0

In [59]:
sc = StandardScaler()
df.iloc[:,0:3] = sc.fit_transform(df.iloc[:,0:3])

In [60]:
covariance_matrix = np.cov([df.iloc[:, 0], df.iloc[:, 1],df.iloc[:,2]])

In [61]:
covariance_matrix

array([[ 1.02040816,  0.11231815,  0.21973428],
       [ 0.11231815,  1.02040816, -0.12923869],
       [ 0.21973428, -0.12923869,  1.02040816]])

In [62]:
eigen_values,eigen_vectors = np.linalg.eig(covariance_matrix)

In [63]:
eigen_values

array([0.70738909, 1.24106951, 1.11276589])

In [64]:
eigen_vectors

array([[ 0.61293896, -0.68350047, -0.39639997],
       [-0.47929008,  0.0772177 , -0.87425308],
       [-0.62816148, -0.72585435,  0.28026526]])

In [65]:
np.dot(eigen_values[0] , eigen_vectors[0][0])

np.float64(0.4335863319252713)

In [66]:
res = np.dot(df.iloc[:,0:3],eigen_vectors[:,0].T)

In [67]:
res = pd.DataFrame(res,columns=['PC'])
res['target'] = df['Target']

In [ ]:
res