In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

# Applying Linear Regression and checking R2score

In [ ]:
from sklearn.datasets import load_diabetes
data = load_diabetes()

In [ ]:
X=data.data
y=data.target

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [ ]:
lr.fit(X_train,y_train)

LinearRegression()

In [ ]:
r2_score(y_test,lr.predict(X_test))

0.5188113124539249

In [ ]:
lr.coef_

array([  23.45465406, -247.42747406,  492.1087518 ,  329.35876431,
       -970.79723039,  573.54295519,  182.42162368,  255.92168168,
        794.21609282,   89.32249214])

In [ ]:
lr.intercept_

np.float64(152.13623331746496)

# Applying Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge
R=Ridge(alpha=10)

In [ ]:
R.fit(X_train,y_train)

Ridge(alpha=10)

In [ ]:
R.coef_ # decrease in betas as we increase lambda

array([ 18.77788374,   0.36423186,  64.21521328,  49.17553459,
        14.4397287 ,   9.62339853, -40.53928043,  39.32153888,
        59.20162298,  40.36525253])

In [ ]:
R.intercept_ # decrease in b when alpha = 10

np.float64(151.96368446414732)

In [ ]:
r2_score(y_test,R.predict(X_test))

0.18324524136176967

# Ridge Regression from Scratch

In [ ]:
from sklearn.datasets import make_regression

In [ ]:
X1,y1=make_regression(n_samples=100,n_features=1,n_informative=1,n_targets=1,noise=20,random_state=13)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X1,y1,test_size=0.2,random_state=45)

In [ ]:
lr1 = LinearRegression()
lr1.fit(X_train,y_train)
lr1.coef_

array([28.2336575])

In [ ]:
lr1.intercept_

np.float64(-2.160744361188285)

In [ ]:
r = Ridge(alpha=10)
r.fit(X_train,y_train)
r.coef_

array([24.7013218])

In [ ]:
r.intercept_

np.float64(-1.9723373693450363)

# Ridge class for 1D data

In [ ]:
class MyRidge:
  def __init__(self,alpha):
    self.m = 0
    self.b = 0
    self.a = alpha

  def fit(self,X_train,y_train):
    num = 0
    den = 0
    for i in range(X_train.shape[0]):
      num+=(y_train[i] - np.mean(y_train)) * (X_train[i] - np.mean(X_train))
      den+=  ((X_train[i] - np.mean(X_train))**2)
    self.m = num/(den+self.a)
    self.b = np.mean(y_train) - (self.m * np.mean(X_train))


  def predict(self,X_test):
    return (self.m * X_test) + self.b

In [ ]:
myridge = MyRidge(10)

In [ ]:
myridge.fit(X_train,y_train)

In [ ]:
myridge.b

array([-1.97233737])

In [ ]:
myridge.m

array([24.7013218])

# Multiple Ridge Regression class for N d Data

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [ ]:
class MyMultipleReg:
  def __init__(self,alpha):
    self.coef_ = None
    self.intercept_ = None
    self.a = alpha

  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis=1)
    identitiy_matrix = np.identity(X_train.shape[1])
    result = np.dot(np.linalg.inv(((identitiy_matrix*self.a )+ np.dot(X_train.T,X_train))),np.dot(X_train.T,y_train))
    self.intercept_ = result[0]
    self.coef_ = result[1:]

  def predict(self,X_test):
    return np.dot( X_test,self.coef_ ) + self.intercept_

In [ ]:
mymlreg = MyMultipleReg(0.1)

In [ ]:
mymlreg.fit(X_train,y_train)

In [ ]:
mymlreg.coef_

array([  44.04252774, -241.72019592,  452.99153345,  332.06044266,
        -76.32617866,  -68.54884462, -165.01664054,  149.93980143,
        431.59483654,   58.54419942])

In [ ]:
mymlreg.intercept_

np.float64(150.84762720023167)

# Gradient Descent ridge regression

creating own class

In [ ]:
class MyGradientDescentRidgeRegression:
  def __init__(self,alpha,epochs,learning_rate):
    self.epochs = epochs
    self.lr = learning_rate
    self.coef_ = None
    self.intercept_ = None
    self.alpha = alpha

  def fit(self,X_train,y_train):
    X_train = np.insert(X_train,0,1,axis=1)
    # self.coef_ = np.ones(X_train.shape[1])
    # self.intercept_ = 0
    betas = np.ones(X_train.shape[1])
    for i in range(self.epochs):
      slope = np.dot(np.dot(X_train.T,X_train),betas) - np.dot(X_train.T,y_train) + self.alpha * betas
      betas =  betas - (self.lr * slope)


    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self,X_test):
    return np.dot(X_test,self.coef_) + self.intercept_


In [ ]:
myridgegd = MyGradientDescentRidgeRegression(0.001,500,0.005)

In [ ]:
myridgegd.fit(X_train,y_train)

In [ ]:
myridgegd.coef_

array([  46.65031169, -221.37470758,  452.12081032,  325.54237291,
        -29.09471027,  -96.4750589 , -190.89988558,  146.32919993,
        400.80287109,   95.09022368])

In [ ]:
myridgegd.intercept_

np.float64(150.86975455006385)