**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [4]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [5]:
import numpy as np

a = np.array([0 for i in range(10)])
a[4] = 1
print(type(a))

b = np.zeros(10)
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
import numpy as np

a,b = tuple(map(int,input("Enter a x b: ").split()))

array = np.random.random((a,b))
print(array)

print(np.average(array))



Enter a x b: 2 3
[[0.68999373 0.69526462 0.29694385]
 [0.0328236  0.51165047 0.77880182]]
0.500913014744251


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [7]:
import numpy as np

def create_2d(a,b):
  array = np.ones((a,b))
  array[1:-1,1:-1] = 0
  return array


a,b = tuple(map(int,input("Enter a x b: ").split()))
print(create_2d(a,b))

Enter a x b: 2 3
[[1. 1. 1.]
 [1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [8]:
import numpy as np

a = np.arange(0.1,1,0.09)
print(a)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [9]:
import numpy as np



a = np.identity(4)
print(a)

# we can only create identity matrix of same size either 3,3 or 4,4 not 3,4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [10]:
import numpy as np
a = np.tile(np.arange(5).reshape(1,5),(5,1))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [11]:
import numpy as np
import math

a = np.random.randint(1,101,size=(10,2))
point = np.array([2,3])

b = np.zeros(10,dtype=int)
for i in range(10):
    sqr = np.sqrt((np.square(a[i][0] - point[0]) + (np.square(a[i][1] - point[1]))) )
    b[i] = int(sqr)

print(b)

[66 64 86 64 18 56 93 99 61 29]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [12]:
import numpy as np


a = np.arange(336).reshape(6,7,8)
index = np.where(a == 100)
x,y,z = index
print(*x,*y,*z)

b = np.unravel_index(100,(6,7,8))
b

1 5 4


(np.int64(1), np.int64(5), np.int64(4))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [13]:
import numpy as np


a = '1 2 3 4 -8 -10'
ans = np.flip(np.array(a.split(),dtype=float))
print(ans)

[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [14]:
import numpy as np


a = np.array([[[3,1],[1,2],[4,5]]])
print(a.size)

6


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [15]:
import numpy as np


class Dimension_mismatch(Exception):
    def __init__(self,message):
        print(message)


def softmax(arr):
    a = np.array(arr,dtype=float)
    try:
        if a.ndim == 1:
            a = np.exp(a)/np.sum(np.exp(a))
            return a
        else:
            raise Dimension_mismatch('Enter 1D array')
    except Dimension_mismatch:
        return



print(softmax([2,1,0.1]))

[0.65900114 0.24243297 0.09856589]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [16]:
import numpy as np

def vertical_stack(*args):
    for arg in args:
        if type(arg) != np.ndarray:
            raise TypeError("only Numpy array required")
    return np.vstack((*args,))

c = np.array(([1,2,3],[4,5,6],[8,7,9]))
d = np.array(([5,6,7],[8,9,10],[1,23,32]))

print(vertical_stack(c,d))


[[ 1  2  3]
 [ 4  5  6]
 [ 8  7  9]
 [ 5  6  7]
 [ 8  9 10]
 [ 1 23 32]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [17]:
def time_range(start,end):
    start = np.datetime64(start)
    end = np.datetime64(end)
    diff = int((end-start)/np.timedelta64(1,'D'))+1
    data = np.full(diff,start)
    for i in range(diff):
        current_date = np.datetime64(data[i])
        current_date+=i
        data[i] = current_date
    return data

print(time_range(start = '2020-09-15', end = '2020-09-25'))

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [18]:
import numpy as np
a  = np.array([[2,4,6],[1,3,5]],dtype=float)
a-=a.mean(axis=1,keepdims=True)
print(a)

[[-2.  0.  2.]
 [-2.  0.  2.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [19]:
import numpy as np
a = np.arange(20).reshape(5,4)
a[:,[0,-1]] = a[:,[-1,0]]
print(a)

[[ 3  1  2  0]
 [ 7  5  6  4]
 [11  9 10  8]
 [15 13 14 12]
 [19 17 18 16]]


###`Q-16:` Replace odd elements in arrays with -1.

In [20]:
import numpy as np
a = np.arange(9).reshape(3,3)
a[a%2!=0] = -1
print(a)

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [21]:
import numpy as np
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

ans = np.maximum(a,b)
print(ans)

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [22]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7021, 2181, 2287, 1579, 5263],
       [6526, 7947, 5080, 9263, 8968],
       [9220, 5725,  771, 4179, 5018],
       [1274, 5874, 6468, 2095, 2865],
       [6450, 7568,  840, 8522, 6303],
       [9870, 2803, 9591, 4375, 7062],
       [7401, 3374,  716, 7691, 6238],
       [6544, 2080, 5503, 2935, 4496]])

In [23]:
import numpy as np


arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
arr1 = arr1[:,::2]

maxi = np.max(arr1)
mini = np.min(arr1)

diff = maxi-mini

arr1 = np.divide((arr1-mini),diff)

print(arr1)

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [24]:
import numpy as np

def max_element(arr,n):
    reverse = list(reversed(np.sort(arr)))
    return reverse[n-1]




arr = np.array([12,34,40,7,1,0])
print(max_element(arr,2))

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [26]:
import numpy as np

a = np.array([1,2,3])

ans = np.hstack((np.repeat(a,3),np.tile(a,3)))
print(ans)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
