###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
import numpy as np

x = np.array([[92, 90 ,74],[ 6, 63 ,93],[15, 93 ,96],[70, 60, 48]])

x

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [2]:
np.sort(x)


array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [3]:
import numpy as np

y = np.array([[92, 90 ,74],[ 6, 63 ,93],[15, 93 ,96],[70, 60, 48]])

y

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [4]:
y[y[:,1].argsort()]

array([[70, 60, 48],
       [ 6, 63, 93],
       [92, 90, 74],
       [15, 93, 96]])

In [5]:
import numpy as np

z = np.array([[92, 90 ,74],[ 6, 63 ,93],[15, 93 ,96],[70, 60, 48]])

z

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [6]:
z = np.array(sorted(z,key=lambda x : max(x),reverse=True))
z

array([[15, 93, 96],
       [ 6, 63, 93],
       [92, 90, 74],
       [70, 60, 48]])

In [7]:
import numpy as np

e = np.array([[92, 90 ,74],[ 6, 63 ,93],[15, 93 ,96],[70, 60, 48]])

e

array([[92, 90, 74],
       [ 6, 63, 93],
       [15, 93, 96],
       [70, 60, 48]])

In [8]:
np.sort(e.flatten()).reshape(4,3)

array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [9]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [10]:
marks = np.concatenate((marks,np.array([41, 87, 72, 36, 92]).reshape(5,1)),axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [11]:
marks = np.concatenate((marks,np.array([77, 83, 98, 95, 89]).reshape(1,5),np.array([92, 71, 52, 61, 53]).reshape(1,5)),axis=0)

In [12]:
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [13]:
a= []
for i in range(len(marks)):
  a.append(np.sum(marks[i:i+1,:]))
a = np.array(a)


In [14]:

marks = np.concatenate((marks,a.reshape(7,1)),axis=1)


In [15]:
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [28]:
marks[marks[:,-1].argsort()][::-1][:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [29]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [34]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [35]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [36]:
# code here
arr = np.arange(6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
np.flip(arr,axis=None)

array([[5, 4, 3],
       [2, 1, 0]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [46]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
arr

array([[ 1,  2,  3,  4,  5],
       [10, -3, 30,  4,  5],
       [ 3,  2,  5, -4,  5],
       [ 9,  7,  3,  6,  5]])

In [91]:
condition = (arr>6)
a = np.array(np.amax(arr.astype(float),axis=1,where=condition,initial=-np.inf))
ans = [x for x,i in enumerate(a) if i!=-np.inf]
ans


[1, 3]

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [19]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [98]:
np.concatenate((arr1,arr2.flatten(),arr3.flatten()),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [99]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

In [112]:
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [122]:
arr[np.where((arr==np.max(arr)) |(arr==np.min(arr)) )]

array([915, 124])

In [123]:
a = np.delete(arr,np.where((arr==np.max(arr)) |(arr==np.min(arr)) ))

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [126]:
arr = np.random.randint(1,600,40)

In [128]:
arr = np.clip(arr,a_min=100,a_max=200)


In [132]:
arr = np.sort(arr)

In [133]:
np.cumsum(arr)

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000, 1119,
       1252, 1390, 1552, 1752, 1952, 2152, 2352, 2552, 2752, 2952, 3152,
       3352, 3552, 3752, 3952, 4152, 4352, 4552, 4752, 4952, 5152, 5352,
       5552, 5752, 5952, 6152, 6352, 6552, 6752])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [143]:
arr = np.random.random(10)
arr

array([0.51948285, 0.80207045, 0.44892812, 0.01461995, 0.3389353 ,
       0.64633534, 0.78664379, 0.93720788, 0.39527068, 0.10869705])

In [144]:
arr = np.round(arr,3)

In [145]:
arr

array([0.519, 0.802, 0.449, 0.015, 0.339, 0.646, 0.787, 0.937, 0.395,
       0.109])

In [146]:
print(np.percentile(arr,0) == np.min(arr))

True


In [147]:
print(np.percentile(arr,100) == np.max(arr))

True


In [152]:
np.round(np.percentile(arr,51)-np.percentile(arr,50),3)

np.float64(0.006)