Numpy Tricks

np.sort
Return Sorted copy in array

In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([32, 87, 73, 79, 50, 42, 61, 48, 40, 92, 61, 19, 72, 31, 93])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[43, 92, 65, 19],
       [60, 68,  9, 58],
       [73, 58, 53, 56],
       [84, 15, 77,  1],
       [38, 50, 60, 50],
       [70, 18, 89, 68]])

In [4]:
np.sort(a)

array([19, 31, 32, 40, 42, 48, 50, 61, 61, 72, 73, 79, 87, 92, 93])

In [5]:
np.sort(b,axis=0)

array([[38, 15,  9,  1],
       [43, 18, 53, 19],
       [60, 50, 60, 50],
       [70, 58, 65, 56],
       [73, 68, 77, 58],
       [84, 92, 89, 68]])

reverse

In [6]:
np.sort(a)[::-1]

array([93, 92, 87, 79, 73, 72, 61, 61, 50, 48, 42, 40, 32, 31, 19])

Append

In [7]:
np.append(a,200)

array([ 32,  87,  73,  79,  50,  42,  61,  48,  40,  92,  61,  19,  72,
        31,  93, 200])

In [8]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[43., 92., 65., 19.,  1.],
       [60., 68.,  9., 58.,  1.],
       [73., 58., 53., 56.,  1.],
       [84., 15., 77.,  1.,  1.],
       [38., 50., 60., 50.,  1.],
       [70., 18., 89., 68.,  1.]])

Concatenate

In [9]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Np.Unique

In [11]:
e = np.array([1,1,1,1,2,2,2,3,3,3])
np.unique(e)

array([1, 2, 3])

Np.expand Dims

In [12]:
a=np.arange(10)
np.expand_dims(a,axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Np.Where


In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.where(a%2==0,0,a)

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

np.argmax

In [15]:
np.argmax(a)

np.int64(9)

In [16]:
b

array([[43, 92, 65, 19],
       [60, 68,  9, 58],
       [73, 58, 53, 56],
       [84, 15, 77,  1],
       [38, 50, 60, 50],
       [70, 18, 89, 68]])

In [17]:
np.argmax(b,axis=0)

array([3, 0, 5, 5])

np.argmin

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.argmin(a)

np.int64(0)

np.cumsum

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [22]:
np.cumprod(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
b


array([[43, 92, 65, 19],
       [60, 68,  9, 58],
       [73, 58, 53, 56],
       [84, 15, 77,  1],
       [38, 50, 60, 50],
       [70, 18, 89, 68]])

In [24]:
np.cumsum(b,axis=1) # 1 means row 0 means column

array([[ 43, 135, 200, 219],
       [ 60, 128, 137, 195],
       [ 73, 131, 184, 240],
       [ 84,  99, 176, 177],
       [ 38,  88, 148, 198],
       [ 70,  88, 177, 245]])

np.percentile

In [25]:
a = np.array([10,34,56,23,78,86,92,34,96,43,57,87])
a

array([10, 34, 56, 23, 78, 86, 92, 34, 96, 43, 57, 87])

In [28]:
np.percentile(a,50)

np.float64(56.5)

In [29]:
np.median(a)

np.float64(56.5)

Np.Histogram

In [30]:
a

array([10, 34, 56, 23, 78, 86, 92, 34, 96, 43, 57, 87])

In [31]:
np.histogram(a,bins=[0,50,100])

(array([5, 7]), array([  0,  50, 100]))

Np.corrcoef

In [38]:
a = np.array([2000,2100,3000])
b = np.array([1,2,3])

In [39]:
np.corrcoef(a,b)

array([[1.       , 0.9078413],
       [0.9078413, 1.       ]])

Np.isin

In [40]:
a

array([2000, 2100, 3000])

In [44]:
np.isin(a,2000)


array([ True, False, False])

Np.Flip

In [45]:
a

array([2000, 2100, 3000])

In [46]:
np.flip(a)

array([3000, 2100, 2000])

In [49]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
np.flip(b,axis=1) # 1 for row 0 for column

array([[2, 1, 0],
       [5, 4, 3]])

Np.put

In [53]:
a

array([2000, 2100, 3000])

In [56]:
np.put(a,[0,1],[2,100])

In [57]:
a

array([   2,  100, 3000])

Np.Delete

In [58]:
a

array([   2,  100, 3000])

In [59]:
np.delete(a,1)

array([   2, 3000])

Set function

intersection

union

set xor

isin

set difference

In [60]:
a = np.arange(6)
b = np.array([2,3,7,8])

In [61]:
np.union1d(a,b)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [62]:
np.intersect1d(a,b)

array([2, 3])

In [63]:
np.setxor1d(a,b)

array([0, 1, 4, 5, 7, 8])

In [64]:
np.setdiff1d(a,b)

array([0, 1, 4, 5])

In [67]:
np.isin(a,1)

array([False,  True, False, False, False, False])

Clip

In [68]:
a

array([0, 1, 2, 3, 4, 5])

In [70]:
np.clip(a,a_max=5,a_min=2)

array([2, 2, 2, 3, 4, 5])

In [71]:
a[np.clip(a,a_max=5,a_min=2)]

array([2, 2, 2, 3, 4, 5])