In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b  = np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [5]:
c = np.array([[[1,2],[3,4],[5,6]]],dtype=str)
c

array([[['1', '2'],
        ['3', '4'],
        ['5', '6']]], dtype='<U1')

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random((3,4))

array([[0.61712029, 0.38498911, 0.53381015, 0.86277344],
       [0.14565319, 0.35797991, 0.51991517, 0.63650693],
       [0.62310354, 0.68871263, 0.58813959, 0.85774376]])

In [11]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
a1 = np.arange(1,10)
a2 = np.arange(1,11).reshape(2,5)
a3 = np.arange(1,9).reshape(2,2,2)

a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.shape

(9,)

In [18]:
a2.shape

(2, 5)

In [19]:
a3.shape

(2, 2, 2)

In [20]:
a3.size

8

In [21]:
a2.size

10

In [22]:
a3.itemsize


8

In [23]:
a1.dtype

dtype('int64')

In [24]:
a2.dtype

dtype('int64')

In [25]:
a3.dtype

dtype('int64')

In [26]:
a1.astype(np.int32)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Array Operations

In [27]:
a1=np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

scalar operation

In [28]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

Relational operator

In [29]:
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

vector operation

In [30]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Arrray FUnctions

In [31]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[53., 40., 60.],
       [69., 74., 71.],
       [72., 74., 91.]])

max

In [32]:
np.max(a1,axis=1)

array([60., 74., 91.])

min

In [33]:
np.min(a1)

np.float64(40.0)

prod

In [34]:
np.prod(a1)

np.float64(2.23579447693056e+16)

Statistical functions

In [35]:
np.mean(a1,axis=0)

array([64.66666667, 62.66666667, 74.        ])

In [36]:
np.median(a1)

np.float64(71.0)

In [37]:
np.var(a1)

np.float64(188.09876543209873)

In [38]:
np.sin(a1)

array([[ 0.39592515,  0.74511316, -0.30481062],
       [-0.11478481, -0.98514626,  0.95105465],
       [ 0.25382336, -0.98514626,  0.10598751]])

dot product

In [39]:
# like we have 2 matrix of shape (3,4),(4,3)
# so final shape of this woud be if 1st column == 2nd row than dot product is possible
# so final shape (3,3) (merge both 1st row with 2nd column)

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

Log and Exponents

In [41]:
np.log(a1)

/tmp/ipython-input-41-2387409814.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [42]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

Round , ceil floor

In [43]:
np.round(np.random.random((3,4))*100)

array([[81., 61., 59., 25.],
       [97., 87., 46., 50.],
       [87., 65., 43., 45.]])

In [44]:
np.ceil(np.arange(1,11)/2)

array([1., 1., 2., 2., 3., 3., 4., 4., 5., 5.])

In [45]:
np.floor((np.arange(1,11))/2)

array([0., 1., 1., 2., 2., 3., 3., 4., 4., 5.])

Indexing and Slicing

In [46]:
a1 = np.arange(1,10)
a2 = np.arange(1,11).reshape(2,5)
a3 = np.arange(1,9).reshape(2,2,2)


In [47]:
a1[-1]

np.int64(9)

In [48]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
a2[1,0]

np.int64(6)

In [50]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
a3[1,0,1]

np.int64(6)

Slicing

In [52]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5]

array([3, 4, 5])

In [54]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
a2[:,2]

array([3, 8])

In [56]:
a2[0,2:3]

array([3])

In [57]:
a2[::1,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [58]:
a4 = np.arange(0,12).reshape(3,4)

In [59]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a4[1,::3]

array([4, 7])

In [61]:
a4[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [62]:
a3 = np.arange(27).reshape(3,3,3)

In [63]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a3[1,1]

array([12, 13, 14])

In [65]:
a3[1,:,1]

array([10, 13, 16])

In [66]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [67]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [68]:
a1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
for i in a1:
  print(i)

1
2
3
4
5
6
7
8
9


In [70]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
for i in a2:
  print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [72]:
for i in np.nditer(a2):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [73]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [74]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [75]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [76]:
np.transpose(a2)# transpose
a2.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [77]:
#ravel convert 2d/3d to 1d
a2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [79]:
a6 = np.arange(12).reshape(3,4)
a7 = np.arange(12,24).reshape(3,4)

In [80]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [82]:
np.hstack((a6,a7,a6))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [83]:
np.vstack((a6,a7))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [85]:
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.hsplit(a6,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [88]:
np.vsplit(a6,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]